INSERT INTO TODO (TITLE,COMPLETED) VALUES ('Hello Collins',0);
INSERT INTO TODO (TITLE,COMPLETED) VALUES ('Java Todo App',0);
INSERT INTO TODO (TITLE,COMPLETED) VALUES ('Do react with spring rest api',0);
